name: 喜马拉雅极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '15 3 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/YiYu.git ~/js
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: npm install
        if: env.XMLY_SPEED_COOKIE
        run: |
          cd ~/js
          git checkout xmly
          pip  install request
      - name: '运行 【喜马拉雅极速版】'
        if: env.XMLY_SPEED_COOKIE
        run: |
          cd ~/js
          node xmly_speed.py
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
